unit    
  ltexts;

interface
  
  const
    C_STR_BANNER = 'LRT lsystem runtime v%0 (%1)';
    C_STR_LSYSTEM_VERSION = '1.0';
    C_STR_LSYSTEM_CODENAME = 'Ragamuffin';
    C_STR_BUILD_TS = 'Build date: %0 %1';
    C_STR_LOADING_BINARY = 'Loading binary "%0"';
    C_STR_NOW_RUNNING = 'Now running - press ESC to stop';
    C_STR_BINARY_NOT_FOUND = 'Binary file not found';
    C_STR_BINARY_INVALID = 'Invalid binary file';
    C_STR_BINARY_TOO_BIG = 'Binary file too big';

implementation

end.