unit    
  ltexts;

interface
  
  const
    C_STR_BANNER = 'LRT lean system runtime v%0 (%1)';
    C_STR_BUILD_TS = 'Build date: %0 %1';
    C_STR_LOADING_BINARY = 'Loading binary "%0"';
    C_STR_NOW_RUNNING = 'Now running';
    C_STR_BINARY_NOT_SPECIFIED = 'Binary file not specified';
    C_STR_BINARY_NOT_FOUND = 'Binary file not found';
    C_STR_BINARY_INVALID = 'Invalid binary file';
    C_STR_BINARY_TOO_BIG = 'Binary file too big';
    C_STR_ADDED_DEVICE = 'Device %1: %0';
    C_STR_INIT_MEMORY_WITH_SIZE = '%0 bytes system memory';

implementation

end.