{
  GAttribs Unit
  2022 LRT
}
unit
  GAttribs;

interface

  const
    C_ATTR_TYPE                 = 'type';
    C_ATTR_ID                   = 'id';
    C_ATTR_FRAME_X              = 'frame.x';
    C_ATTR_FRAME_Y              = 'frame.y';
    C_ATTR_FRAME_WIDTH          = 'frame.width';
    C_ATTR_FRAME_HEIGHT         = 'frame.height';
    C_ATTR_BORDER_STYLE         = 'border-style';
    C_ATTR_BORDER_STYLE_RAISED  = 'raised';
    C_ATTR_BORDER_STYLE_LOWERED = 'lowered'; 
    C_ATTR_BACKGROUND_COLOR     = 'background-color';
    C_ATTR_CONTROLS             = 'controls';

    C_CONTROL_TYPE_PANEL = 'panel';

implementation

end.
