{
  GAttribs Unit
  2022 LRT
}
unit
  GAttribs;

interface

  const
    C_ATTR_TYPE                 = 'type';
    
    C_ATTR_ID                   = 'id';
    
    C_ATTR_BORDER_STYLE         = 'border-style';
    C_ATTR_BORDER_STYLE_RAISED  = 'raised';
    C_ATTR_BORDER_STYLE_LOWERED = 'lowered'; 
    
    C_ATTR_BACKGROUND_COLOR     = 'background-color';

    C_ATTR_BACKGROUND_STYLE     = 'background-style';
    C_ATTR_BACKGROUND_STYLE_SOLID = 'solid';
    C_ATTR_BACKGROUND_STYLE_TRANSPARENT = 'transparent';
    
    C_ATTR_CONTROLS             = 'controls';

    C_ATTR_ALIGN           = 'align';
    C_ATTR_TEXT_ALIGN      = 'text-align';
    C_ATTR_ALIGN_TL        = 'top-left';
    C_ATTR_ALIGN_TOP       = 'top';
    C_ATTR_ALIGN_TR        = 'top-right';
    C_ATTR_ALIGN_LEFT      = 'left';
    C_ATTR_ALIGN_CENTER    = 'center';
    C_ATTR_ALIGN_RIGHT     = 'right';
    C_ATTR_ALIGN_BL        = 'bottom-left';
    C_ATTR_ALIGN_BOTTOM    = 'bottom';
    C_ATTR_ALIGN_BR        = 'bottom-right';
    
    C_ATTR_TEXT                 = 'text';
    C_ATTR_TEXT_COLOR           = 'text-color';
    C_ATTR_PLACEHOLDER          = 'placeholder';

    C_ATTR_CAPTION              = 'caption';

    C_ATTR_CHECKED              = 'checked';

    C_ATTR_TITLE                = 'title';

    C_PATH_FRAME_X              = 'frame.x';
    C_PATH_FRAME_Y              = 'frame.y';
    C_PATH_FRAME_WIDTH          = 'frame.width';
    C_PATH_FRAME_HEIGHT         = 'frame.height';

    C_CONTROL_TYPE_CONTROL  = 'control';
    C_CONTROL_TYPE_PANEL  = 'panel';
    C_CONTROL_TYPE_LABEL  = 'label';
    C_CONTROL_TYPE_BUTTON = 'button';
    C_CONTROL_TYPE_CHECKBOX = 'checkbox';
    C_CONTROL_TYPE_TEXTFIELD = 'textfield';

implementation

end.
