{
  gclasses Unit
  Class IDs for objects extending TObject
  2022 LRT
}
unit
  gclasses;

interface

  const
    C_CLASS_ID_GUI             = 2000;
    C_CLASS_ID_CONTROLFACTORY  = 2001;
    C_CLASS_ID_RENDERER        = 2002;
    C_CLASS_ID_METEOR          = 2003;
    C_CLASS_ID_COLORSCHEME     = 2004;
    C_CLASS_ID_FORM            = 2005;

    { control family }
    C_CLASS_ID_CONTROL        = 2011;
    C_CLASS_ID_PANEL          = 2012;
    C_CLASS_ID_LABEL          = 2013;
    C_CLASS_ID_BUTTON         = 2014;
    C_CLASS_ID_CONTROL_FAMILY = 2020;

implementation

end.