{
  gclasses Unit
  Class IDs for objects extending TObject
  2022 LRT
}
unit
  gclasses;

interface

  const
    C_CLASS_ID_GUI             = 2000;
    C_CLASS_ID_CONTROLFACTORY  = 2001;
    C_CLASS_ID_RENDERER        = 2002;
    C_CLASS_ID_METEOR          = 2003;
    C_CLASS_ID_COLORSCHEME     = 2004;
    C_CLASS_ID_GUIAPP          = 2007;

    C_CLASS_ID_FORM_FROM       = 2100;
    C_CLASS_ID_FORM            = 2101;
    C_CLASS_ID_ALERTFORM       = 2102;
    C_CLASS_ID_FORM_TO         = 2200;

    { control family }
    C_CLASS_ID_CONTROL        = 2011;
    C_CLASS_ID_PANEL          = 2012;
    C_CLASS_ID_LABEL          = 2013;
    C_CLASS_ID_BUTTON         = 2014;
    C_CLASS_ID_CHECKBOX       = 2015;
    C_CLASS_ID_TEXTFIELD      = 2016;
    C_CLASS_ID_CONTROL_FAMILY = 2020;

implementation

end.