unit
  tpstring;

interface

  const
    C_STR_VERSION = '0.1';
    C_STR_WELCOME = 'TPBuild ' + C_STR_VERSION + ' made by LRT in (2024)';
    C_STR_TPC_NOT_INSTALLED = 'TPC not installed or not set in the DOS path';
    C_STR_TPC_LOCATION = 'Turbo Pascal compiler location: ';
    C_STR_PROJECT_DIR = 'Project directory: ';
    C_STR_CURRENT_DIR = '(current)';
    C_STR_BUILD_ALL = 'Building all';

implementation

end.