{
  this unit contains all the localized texts of the lsystem assembly compiler
}
unit 
  ltexts;

interface

  const
    C_STR_BANNER = 'LASMC lsystem assembly compiler version %0';
    C_STR_BUILD_TS = 'Built on %0 at %1';
    C_STR_NO_SOURCE_FILE = 'No source file specified!';
    C_STR_BUILDING = 'Building...';
    C_STR_READ_ERROR = 'Could not read source code!';
    C_STR_SENTENCES_PROC = '%0 sentences read';
    C_STR_SENTENCE_OPERATION = 'operation %0 (%1)';
    C_STR_SENTENCE_PARAMETER = '   param %0 (%1)';
    C_STR_MAKING = 'making object file';
    C_STR_SAVING = 'saving object file';

implementation

end.